# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XEP6XZkPRQMUQX4BeuIAHiHn26Qad26C
"""

# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12GqGAjmeuNkk5aJSXJOuj3GNzYTNTOp1
"""

import streamlit as st
import os
import time
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from typing import List, Dict
from datetime import datetime
from openai import OpenAI

# =============================================================================
# PAGE CONFIGURATION
# =============================================================================

st.set_page_config(
    page_title="Trustworthy AI Explainer",
    page_icon="🤖",
    layout="wide",
    initial_sidebar_state="expanded"
)

# =============================================================================
# LLM CONFIGURATION
# =============================================================================

@st.cache_resource
def load_llm():
    """
    Load OpenAI client (cached).
    Uses API key provided in the app sidebar.
    """
    api_key = st.session_state.get("OPENAI_API_KEY", None)
    if not api_key:
        st.error("⚠️ No se ha configurado la API Key. Por favor introdúcela en la barra lateral.")
        return None
    return OpenAI(api_key=api_key)

# =============================================================================
# CACHED DATA FUNCTIONS
# =============================================================================

@st.cache_data(ttl=3600)
def load_feedback_data() -> pd.DataFrame:
    if 'feedback_db' in st.session
